### PR TITLE
Add --no-tty option to gpg commands

### PR DESCRIPTION
**Pull request by iggy**
Not sure what the difference is, but sometimes gpg complains about not having a
tty. Sometimes it works fine. Let's just go ahead and be on the safe side and
add --no-tty option to all gpg calls.

### CODE REVIEW

**Comment by babilen** [comment]
I really have problems making sense of your PRs as the mostly contain the same commits. Could you untangle them and get rid of "internal" development ones such as "Merge branch 'master' of github.com:iggy/aptly-formula" ?

**Comment by iggy** [comment]
As I said in the other PR (and the comments for all the PRs after this one), the extra commits don't show up if you merge them in order. I'm honestly not too worried whether you merge these or not. They are already in the copy we use.

**Comment by whiteinge** [comment]
@iggy great fixes in #4, #6, and #7. Thanks for sending them. In the future if you have multiple changes that depend on each other, feel free to send them in a single pull req. It makes it easier for people reviewing the changes since GitHub's interface doesn't easily let you compare different pull requests.

**Comment by iggy** [comment]
lol... I was actually told the opposite before. I'll try to just have one open at a time from now on.

**Comment by whiteinge** [comment]
Hm. Sorry for the mixed messages. I'd say it's best to separate unrelated changes into separate branches and separate pull reqs where possible, but when change 'B' depends on change 'A' they should be in the same pull req. My $0.02 anyway.

**Pull request merged**
